### ISSUE TITLE
Volume control with command

### ISSUE THREAD

**Issue by S--Minecraft** [FlareBot/FlareBot#108]
For me, the volume is too large.
I set the user volume of the bot to 1% but it is still large.
If there is an command that can control the volume, it will be great.

example. `_volume 10` `_volume 20%`

or if it is able to implement ReplayGain feature it would be so cool

thanks for developing this wonderful bot

**Comment by binaryoverload** [comment]
We got rid of the volume control feature because it used too much CPU, we might implement it when we get nodes sorted but right now any audio adjustment features is a no.
