### ISSUE TITLE
join command when not in voice channel

### ISSUE THREAD

**Issue by Judaxx** [FlareBot/FlareBot#166]
if you try to do the 'join' command when not in a voice channel the bot simply deletes the message and does nothing (as expected, I guess), but maybe it should also send a message back to the user requesting it, letting them know that they should be in a voice channel before calling the join command.

**Comment by WalshyDev** [comment]
Done in commit 771348d15dcdb92d32cbfbf569c82e680098e44f, will be pushed today at 12pm GMT aka~2 hours.
