### ISSUE TITLE
 Unbanning seems to trip over 

### ISSUE THREAD

**Issue by PainDessert** [FlareBot/FlareBot#173]
Command linked: _unban
Error: That user isn't in this server!
Why its a bug: It fails to unban a user that has been banned.

**Comment by WalshyDev** [comment]
Looking into it.

**Comment by PainDessert** [comment]
Okay

**Comment by WalshyDev** [comment]
Issue should be fixed, let me know it is after the usual update time!

**Comment by WalshyDev** [comment]
Fix confirmed working, closed.
