### ISSUE TITLE
Kicking bots/users can sometimes fail

### ISSUE THREAD

**Issue by PainDessert** [FlareBot/FlareBot#176]
Command linked: _kick
Error: That user is not on this server therefore cannot be kicked!
What it should do: Kick the user given..
How I got to this: Without @ or by using the id of that user it can fail. 
Possible fix: Fix the issue that I literally just listed..
Something to show what I just said...
![image](https://user-images.githubusercontent.com/36565735/37231190-31080734-23e2-11e8-8834-28ccd86a66e3.png)

**Comment by weeryan17** [comment]
Please fallow the issue template for future issues. Yes they're a pain in the but to write but they hep our so much

**Comment by WalshyDev** [comment]
This is fixed and being pushed in 4.2!
