### ISSUE TITLE
_help <category> not work

### ISSUE THREAD

**Issue by PainDessert** [FlareBot/FlareBot#185]
## Expected Behavior

using something like _help music should give music commands,
## Current Behavior

 but all it gives is "No such category!"
## Possible Solution

This seemed to happen after the 19.3.18 restart (This should probably have gone the day before, but idk)
## Steps to Reproduce

[How?]
https://pasteboard.co/HcFU80i.png
[Oh and that's done with * (Server owner)]

1. If you do `_help general`, `_help music` etc.
2. This produces an error saying no such category  

## Context (Environment)

FlareBot 4.2, Shard 11
## Detailed Description

To report an issue???
## Possible Implementation
no idea

(I have too much time on my hands)

**Comment by weeryan17** [comment]
`(I have too much time on my hands)` clearly not with these bad issues :P

**Comment by PainDessert** [comment]
Oi

**Comment by PainDessert** [comment]
(I edited that and watch Walshy complain too somehow again)

**Comment by WalshyDev** [comment]
Fixed in 217d6fb4e24cf366b8a5ac33c369a8241dc3b2d0
Release: today (2pm BST)
