### ISSUE TITLE
No help for permissions

### ISSUE THREAD

**Issue by CraftedPixel** [FlareBot/FlareBot#81]
I don't know how to make it so that Visitors get lower permissions and Members get higher permissions. And the help command doesn't give you a list of commands.

**Comment by binaryoverload** [comment]
@CraftedPixel The permissions system is designed in such a way that you simply make a group (Called Visitor and Member in this case), link a physical role to it if you wish and add and remove permissions as you wish. You will also find that doing `_help` *will* list the commands.

Please join our support guild if you have any further queries: http://discord.me/flarebot
