### ISSUE TITLE
Hacktoberfest 2017 - Looking for contributions

### ISSUE THREAD

**Issue by WalshyDev** [FlareBot/FlareBot#91]
It is that time of the year again. From the 1st October to the 31st October FlareBot will be open for Pull Requests contributing to the [Hacktoberfest](https://hacktoberfest.digitalocean.com/)!
Now before you start going we have some rules for this event in order to avoid spam and bad pull requests.

# Rules

Before you start making changes please view our [CONTRIBUTING.md](https://github.com/FlareBot/FlareBot/blob/master/CONTRIBUTING.md) and make sure to follow that, failure to do so will get your PR denied.

We are not interested in Pull Requests that change a few typos in documentation or symbol names.
We do not want any Pull Requests that are breaking (renaming of classes, methods, etc.)
Pull Requests that are obviously split up to farm will not be accepted and marked as invalid (For example changing docs of 2 classes in 2 Pull Requests is not wanted)
> Once you have opened your Pull Requests we might review and request changes. If no response is given we will mark your PR as invalid and close it. Please keep track of our review process.

# What we are looking for

Additions, updates and improvements to the documentation of FlareBot are always welcome and we are hoping for a lot of contributions in that direction. Note that some things do not need to be documented, it is mostly untils that need this. Code changes are welcome as long
as it is not a breaking change. 

Please open all hacktoberfest pull requests with the base of the `hacktoberfest` branch and target that same branch. 

If you need some ideas on what to do we have a [Trello](https://trello.com/b/7ucxPoko/flarebot) you can use to see what needs to be done, you can also go to classes like [GeneralUtils](https://github.com/FlareBot/FlareBot/blob/hacktoberfest/src/main/java/stream/flarebot/flarebot/util/GeneralUtils.java) and add documentation to the methods there.

# Notes

Before you start making changes please look at already existing Pull Requests and avoid making duplicates. We recommend commenting on this issue about changes that you are currently working on
to inform other contributors about already in-progress changes. You should also look for any comments yourself that might already be claiming what you want to work on.

**If you are adding a new feature talk to us first so we can verify how it will work, what args there should be etc!**

**Comment by khorne3** [comment]
Hello! I'm interested in helping y'all out with docs, and I'd like to see what you were looking for before I started writing for the sake of writing. I've joined Discord, and I'm obviously here on GitHub -- is there a specific place you'd like to have this discussion?

**Comment by binaryoverload** [comment]
@khorne3 Mention me on discord and we can have a discussion there :D
